[package]
name = "RustSim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
cute = "0.3.0"
ndarray-rand = "0.14.0"
ndarray-csv = "0.5.1"
csv = "1.2.1"